Models/ErrorViewModel.cs
namespace SiteDeVendas.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/ItensVendasModel.cs
using System.ComponentModel.DataAnnotations.Schema;

namespace SiteDeVendas.Models
{
    public class ItensVendasModel
    {
        [ForeignKey("ProdutoID")]
        public int ProdutoID { get; set; }

        public required ProdutosModel Produto { get; set; }

        [ForeignKey("VendaID")]
        public int VendaID { get; set; }

        public required VendasModel Venda { get; set; }

        public int Quantidade { get; set; }

    }
}

Models/ProdutosModel.cs
using System.ComponentModel.DataAnnotations;

namespace SiteDeVendas.Models
{
    public class ProdutosModel
    {
        [Key]
        public int ProdutoID { get; set; }
        public string? Nome { get; set; }
        public string? Tipo { get; set; }
        public int Quantidade { get; set; }
        public bool Ativo { get; set; }
        public float Price { get; set;  }
        //public string imagem { get; set; }

    }
}

Models/UsuariosModel.cs
using System.ComponentModel.DataAnnotations;

namespace SiteDeVendas.Models
{
    public class UsuariosModel
    {
        [Key]
        public int UsuarioID { get; set; }
        public string? Nome { get; set; }
        public DateTime DataNascimento { get; set; } 
        public string? Login { get; set; }
        public string? Senha { get; set; }

    }
}

Models/VendasModel.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SiteDeVendas.Models
{
    public class VendasModel
    {
        [Key]
        public int VendaID { get; set; }
        public int UsuarioID { get; set; }
        [ForeignKey("UsuarioID")]
        public required UsuariosModel Usuario { get; set; }
        public bool Reembolsado { get; set; }
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using SiteDeVendas.Models;
using System.Diagnostics;

namespace SiteDeVendas.Controllers
{
    public class HomeController : Controller
    {

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/ManagerController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SiteDeVendas.Data;
using SiteDeVendas.Interfaces;
using SiteDeVendas.Models;
using SiteDeVendas.Repository;

namespace SiteDeVendas.Controllers
{
    public class ManagerController : Controller
    {
        private readonly IProdutosRepository _produtosRepository;
        private readonly IManagerRepository _managerRepository;


        public ManagerController(IProdutosRepository produtosRepository, IManagerRepository managerRepository) {

            _managerRepository = managerRepository;
            _produtosRepository = produtosRepository;
        }


        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> ManageProducts()
        {
            IEnumerable<ProdutosModel> produtos = await _produtosRepository.GetAll();
            return View(produtos);
        }

        public class Product
        {
            public int id;
            public string name;
            public int quantity;
            public string type;
            public float price;
            public bool active;



        }

        [HttpPost]
        public JsonResult updateProduct([FromBody] ProdutosModel product)
        {

            bool result = _managerRepository.UpdateProduct(product);

            if (result)
            {
                return Json(new
                {

                    //message = $"ID: {product.ProdutoID}     Nome: {product.Nome}        Quantidade: {product.Quantidade}        Type: {product.Tipo}        Price: {product.Price}      Active: {product.Ativo}",
                    message = $"The product has been updated. input: {product.Nome} ",


                });
            }
            else {

                return Json(new
                {
                    //message = $"ID: {product.ProdutoID}     Nome: {product.Nome}        Quantidade: {product.Quantidade}        Type: {product.Tipo}        Price: {product.Price}      Active: {product.Ativo}",
                    message = "ERROR: Something happend and the product can't been updated."
                });
            }
            

        }
    }
}

Controllers/ProdutosController.cs
using Microsoft.AspNetCore.Mvc;
using SiteDeVendas.Data;
using SiteDeVendas.Interfaces;
using SiteDeVendas.Models;
using static System.Runtime.InteropServices.JavaScript.JSType;

namespace SiteDeVendas.Controllers
{
    public class ProdutosController : Controller
    {
        private readonly IProdutosRepository _produtosRepository;

        public ProdutosController(IProdutosRepository produtosRepository)
        {
            _produtosRepository = produtosRepository;
        }
        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> VisualizarProdutos(string tipo)
        {
            IEnumerable<ProdutosModel> produtos = await _produtosRepository.GetByTipoAsync(tipo);

            return View(produtos);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(ProdutosModel produto)
        {
            if (!ModelState.IsValid)
            {
                return View(produto);
            }

            _produtosRepository.Add(produto);
            _produtosRepository.Save();

            return RedirectToAction("Index");
        }

        public class body
        {
            public string nome { get; set; }
            public int number { get; set; }
        }

        [HttpPost]
        public JsonResult Delete(int id, [FromBody] body name)
        {
            var produto =  _produtosRepository.GetById(id);

            if(produto == null)
            {
                return Json(new { success = false, message = $"Erro ao remover produto de id = {id}." });
            }
            
            _produtosRepository.Delete(produto);
            _produtosRepository.Save();

            return Json(new { success = true, message = $"Produto {name.nome} deletado com sucesso." });
        }

        public async Task<IActionResult> Detalhes(int id)
        {
            ProdutosModel produto = await _produtosRepository.GetByIdAsync(id);
            return View(produto);
        }

        public IActionResult Gestor()
        {
            return View();
        }
    }
}

Controllers/UsuariosController.cs
using Microsoft.AspNetCore.Mvc;
using SiteDeVendas.Data;
using SiteDeVendas.Interfaces;
using SiteDeVendas.Models;

namespace SiteDeVendas.Controllers
{
    public class UsuariosController : Controller
    {
        private readonly IUsuariosRepository _usuariosRepository;
        public UsuariosController(IUsuariosRepository usuariosRepository) {
            _usuariosRepository = usuariosRepository;
        }
        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> ShowUsers()
        {
            IEnumerable<UsuariosModel> users = await _usuariosRepository.GetAll();
            return View(users);
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Teste</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Manager/Index.cshtml
<a asp-controller="Manager" asp-action="ManageProducts">Manage Products</a>

Views/Manager/ManageProducts.cshtml
@model IEnumerable<ProdutosModel>

<link href="~/css/Manager/ManageProducts.css" rel="stylesheet" />


<h1>Manage Products</h1>

<div class="MainDiv">


    <div class="GridDiv">

        <p class="ColumnTittle">ID</p>
        <p class="ColumnTittle">Name</p>
        <p class="ColumnTittle">Type</p>
        <p class="ColumnTittle">Quantity</p>
        <p class="ColumnTittle">Price</p>
        <p class="ColumnTittle">Options</p>

        @foreach(var product in Model){
            <p class="GridItem Number" id="productId">@product.ProdutoID</p>
            <p class="GridItem Text">@product.Nome</p>
            <p class="GridItem Text">@product.Tipo</p>
            <p class="GridItem Number">@product.Quantidade</p>
            <p class="GridItem Number">R$ @product.Price</p>
            <button class="GridItem Button" onclick="editProduct('@product.ProdutoID','@product.Nome', '@product.Tipo', @product.Quantidade, '@product.Price', '@product.Ativo')">Edit</button>

        }
    </div>


    <div class="ModalShadow" id="ModalShadow"></div>

        <div class="MainDivModal" id="Modal">

            <h2>Editar Produto</h2>
            <button onclick="closeModal()">X</button>

            <div>

                <div class="ModalDivItem">
                    <label>Name</label>
                <input type="text" name="name" id="productName" value="" />
                </div>

                <div class="ModalDivItem">
                    <label>Type</label>
                    <select id="productType">

                        <option value="Comidas">Comidas</option>
                        <option value="Tech">Tech</option>

                    </select>
                </div>

                <div class="ModalDivItem">
                    <label>Quantity</label>
                <input type="number" name="name" id="productQuantity" value="" />
                </div>

                <div class="ModalDivItem">
                    <label>Price</label>
                <input type="text" name="name" id="productPrice" value="" />
                </div>

                <div class="ModalDivItem">
                    <label>Active</label>

                    <div class="ModalActiveDiv">
                        <label>True: </label>
                        <input id="opTrue" type="radio" name="active" value="1" />
                        <label>False: </label>
                    <input id="opFalse" type="radio" name="active" value="0" />
                    </div>

                </div>

            <button class="updateButton" onclick="updateProduct()">Update</button>

            </div>

        </div>

</div>


<script>

    const modal = document.getElementById("Modal");
    const modalShadow = document.getElementById("ModalShadow");
    let correntProductId = null;

    function editProduct(id, name, type, quantity, price, active){

        modal.style.display = "block";
        modalShadow.style.display = "block";
        currentProductId = id;

        var nameInput = document.getElementById("productName");
        nameInput.value = name;

        var quantityInput = document.getElementById("productQuantity");
        quantityInput.value = quantity;

        var priceInput = document.getElementById("productPrice");
        priceInput.value = price

        document.getElementById("productType").value = type


        switch(active){

            case "True":
                document.getElementById("opTrue").checked = true
                break

            case "False":
                document.getElementById("opFalse").checked = true
                break
        }


        console.log(`${name} ${type} ${quantity} ${price} ${active}`)
        console.log(active)
    }

    function closeModal(){
        modal.style.display = "none";
        modalShadow.style.display = "none";
    }

    function updateProduct(){
        
        var id = currentProductId;
        var name = document.getElementById("productName").value;
        var type = document.getElementById("productType").value;
        var quantity = document.getElementById("productQuantity").value;
        var price = document.getElementById("productPrice").value.replace(",",".");
        var active = null;

        var radios = document.getElementsByName("active");

        for(i = 0; i < radios.length; i++){
            if(radios[i].checked){
                
                switch(radios[i].value){
                    case "1":   active = true
                    break

                    case "0":   active = false
                    break
                }
            }
        }

        //console.log(price)


        $.ajax({
            url: "/Manager/updateProduct",
            method: "POST",
            contentType: "application/json",
            data: JSON.stringify({ProdutoID : id, Nome : name, Tipo: type, Quantidade : quantity, Ativo: active, Price: price}),
            success: function(response){

                console.log(response.message)
            },
            error: function(error){

                console.log(error.message)
            }
        })

    }
</script>

Views/Produtos/Create.cshtml
@model ProdutosModel

<link href="~/css/Produtos/Create.css" rel="stylesheet" />

<h1>Cadastrar Produto</h1>

<form asp-action="Create" method="post">
    
    <div>   
        <label asp-for="Nome">Nome: </label><br />
        <input asp-for="Nome" value=""/>
    </div>

    <div>
        <label asp-for="Tipo">Tipo: </label><br />
        <select  asp-for="Tipo">
            <option value="Comidas">Comidas</option>
            <option value="Tech">Tech</option>
        </select>
    </div>

    <div>
        <label asp-for="Quantidade">Quantidade: </label><br />
        <input asp-for="Quantidade" value="" />
    </div>

    <div>
        <label asp-for="Price">Preço: </label><br />
        <input asp-for="Price" value="" />
    </div>

    <div>
        <label asp-for="Ativo">Ativo: </label><br />
        <input asp-for="Ativo" type="radio" value="true" />
        <label asp-for="Ativo">Sim</label>
        <input asp-for="Ativo" type="radio" value="false" />
        <label asp-for="Ativo">Não</label>
    </div>

    <div class="SubmitDiv">
        <input type="submit" name="submit" value="Cadastrar" />
    </div>

</form>

Views/Produtos/Detalhes.cshtml
@model ProdutosModel

<link href="./css/Produtos/Detalhes.css" rel="stylesheet" />

<h1>@Model.Nome</h1>
<div class="">
    <div class="div_imagem">
        imagem
    </div>
    <div class="div_conteudo">

    </div>
</div>

Views/Produtos/Index.cshtml
@model IEnumerable<ProdutosModel>



<div>

    <div>
        <a asp-controller="Produtos" asp-action="VisualizarProdutos" asp-route-tipo="Comidas">Comidas</a>
    </div>

    <div>
        <a asp-controller="Produtos" asp-action="Create"> Cadastrar Produto</a>
    </div>

    <div>
        <a asp-controller="Produtos" asp-action="VisualizarProdutos" asp-route-tipo="Tech">Tech</a>
    </div>

</div>

Views/Produtos/Tech.cshtml
@model IEnumerable<ProdutosModel>


@{
}

<link href="~/css/Produtos/Produtos.css" rel="stylesheet" />

<div class="div_titulo">
    <h1>Tech</h1>
</div>

<div class="Conteudo">
    @foreach (var item in Model)
    {
        <div class="div_item">
            <div>
                <h4>@item.Nome</h4>
            </div>
            <div>
                <p>R$ @item.Price</p>
            </div>
            <div>
                <button>Comprar</button>
            </div>
        </div>
    }
</div>

Views/Produtos/VisualizarProdutos.cshtml
@model IEnumerable<ProdutosModel>


@{
}

<link href="~/css/Produtos/Produtos.css" rel="stylesheet" />
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

<div class="div_titulo">
    <h1>@Model.First().Tipo</h1>
</div>

<div class="Conteudo">
    @foreach (var item in Model)
    {
        <div class="div_item">

            <div class="div_nome">
                <h4>@item.Nome</h4>
            </div>

            <div class="div_preco">
                <p>R$ @item.Price</p>
            </div>

            <div class="div_botao">
                <a class="btn btn-secondary" asp-controller="Produtos" asp-action="Detalhes" asp-route-id="@item.ProdutoID">Ver Produto</a>
                <button class="btn btn-danger" onclick="Delete(@item.ProdutoID,'@item.Nome')">Excluir</button>
            </div>

        </div>
    }
</div>
<script>

    function Delete(id, name){
        
        console.log(id)

        if(!confirm(`Deseja excluir ${name}?`)){

            return;
        }

            $.ajax({
                  url: `/Produtos/Delete/${id}`,
                  method: "POST",
                  contentType: "application/json",
                  dataType: "json",
                  data: JSON.stringify({nome: name, numero : 55}),
                  success: function(response){
                    alert(response.message)
                  },
                  error: function(error){
                    alert(error.message)
                  }
            });

    }

</script>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Site de Vendas</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SiteDeVendas.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Site de Vendas</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li>
                            <a class="nav-link text-dark" asp-area="" asp-controller="Produtos" asp-action="Index">Produtos</a>
                        </li>
                        <li>
                            <a class="nav-link text-dark" asp-area="" asp-controller="Usuarios" asp-action="ShowUsers">Usuários</a>
                        </li>
                        <li>
                            <a class="nav-link text-dark" asp-area="" asp-controller="Manager" asp-action="Index">Manager</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
     <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - SiteDeVendas - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Usuarios/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<h1>Usuarios Index Page</h1>

Views/Usuarios/ShowUsers.cshtml
@model IEnumerable<UsuariosModel>

<h1>Usuários</h1>

@foreach(var item in Model){
    <h4>@item.Nome</h4>
}